//! Arbitrage signal types and profit calculation.
//!
//! A `CrossChainSingleHop` signal is the central output of the strategy: it captures everything
//! needed to evaluate and execute a two-legged cross-chain arbitrage trade.
//!
//! ## Signal lifecycle
//!
//! 1. Generated by `kuma_core::strategy::CrossChainSingleHop::generate_signal()`
//! 2. Deduped via `ExpectedProfit::same_outcome()` — identical-outcome signals are dropped
//! 3. Queued in `kumad`'s strategy worker until the 75% submission deadline fires
//! 4. Emitted to the execution worker via an `mpsc` channel
//! 5. Promoted to a `Trade` via `CrossChainSingleHop::try_promote()`
//!
//! ## Direction
//!
//! `Direction::AtoB` means selling token A on the slow chain and buying it back on the fast chain.
//! `Direction::BtoA` is the reverse. The optimal direction is determined by binary search over
//! the surplus in both directions — see `strategy::CrossChainSingleHop::generate_signal()`.
//!
//! ## Profit types
//!
//! - [`ExpectedProfit`] — calculated at signal generation time from simulated swap amounts,
//!   with slippage, congestion risk, and gas cost discounts applied.
//! - [`RealizedProfit`] — calculated after trade execution from on-chain receipt logs.

use serde::{Deserialize, Serialize};
use std::{fmt::Display, sync::Arc};
use tycho_simulation::protocol::models::ProtocolComponent;

use color_eyre::eyre::{self, Context, Ok, OptionExt};

use crate::{
    chain::Chain,
    encoder::{UnsignedTransaction, create_solution},
    spot_prices::SpotPrices,
    state::{self, pair::Pair},
    strategy::Swap,
    trade::Trade,
};

pub use profit::bps_discount;

mod profit;

pub use profit::ExpectedProfit;
pub use profit::RealizedProfit;

/// Direction of the slow-chain leg of the arbitrage.
///
/// - `AtoB`: sell token A, receive token B on the slow chain; then sell B, receive A on the fast chain.
/// - `BtoA`: sell token B, receive token A on the slow chain; then sell A, receive B on the fast chain.
///
/// The optimal direction is determined by comparing surplus in both directions via binary search.
// TODO: rename to buy/sell to make the slow-chain perspective clearer
#[derive(Debug, Clone)]
pub enum Direction {
    AtoB,
    BtoA,
}

impl Display for Direction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Direction::AtoB => write!(f, "A to B"),
            Direction::BtoA => write!(f, "B to A"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrossChainSingleHop {
    /// The chain with longer block times where the first leg of the arbitrage executes.
    pub slow_chain: Chain,
    /// Block height on the slow chain when this signal was generated.
    pub slow_height: u64,
    /// The token pair being traded on the slow chain (e.g., WETH/USDC).
    pub slow_pair: Pair,
    /// Unique identifier for the AMM pool on the slow chain.
    pub slow_pool_id: state::PoolId,
    /// Protocol component metadata for the slow chain pool, used for transaction encoding.
    pub slow_protocol_component: Option<Arc<ProtocolComponent>>,
    /// Simulated swap parameters for the slow chain leg (token_in, amount_in, token_out, amount_out).
    pub slow_swap_sim: Swap,
    /// Base fee in wei for slow chain
    pub slow_base_fee: u64,
    /// The chain with shorter block times where the second leg of the arbitrage executes.
    pub fast_chain: Chain,
    /// Block height on the fast chain when this signal was generated.
    pub fast_height: u64,
    /// The token pair being traded on the fast chain (mirrors slow_pair tokens).
    pub fast_pair: Pair,
    /// Unique identifier for the AMM pool on the fast chain.
    pub fast_pool_id: state::PoolId,
    /// Protocol component metadata for the fast chain pool, used for transaction encoding.
    pub fast_protocol_component: Option<Arc<ProtocolComponent>>,
    /// Simulated swap parameters for the fast chain leg (token_in, amount_in, token_out, amount_out).
    pub fast_swap_sim: Swap,
    /// Base fee in wei for fast chain
    pub fast_base_fee: u64,
    /// Spot prices between token A and token B on the slow chain, used for profit calculation.
    pub slow_prices_a_b: SpotPrices,
    /// Spot prices for token A to USDC conversion, None if token A is USDC.
    pub slow_prices_a_usdc: Option<SpotPrices>,
    /// Spot prices for token B to USDC conversion, None if token B is USDC.
    pub slow_prices_b_usdc: Option<SpotPrices>,
    /// Spot prices for ETH to USDC conversion, used for gas cost calculation.
    pub slow_prices_eth_usdc: Option<SpotPrices>,
    /// Maximum acceptable slippage in basis points (1 bps = 0.01%).
    pub max_slippage_bps: u64,
    /// Discount applied to expected profit to account for congestion/settlement risk, in basis points.
    pub congestion_risk_discount_bps: u64,
    /// Calculated expected profit after applying slippage and congestion discounts.
    pub expected_profit: ExpectedProfit,
}

impl CrossChainSingleHop {
    #[allow(clippy::too_many_arguments)]
    pub fn try_from_simulations(
        slow_chain: &Chain,
        slow_pair: &Pair,
        slow_protocol_component: Arc<ProtocolComponent>,
        slow_id: &state::PoolId,
        slow_height: u64,
        slow_swap_sim: Swap,
        slow_prices_a_b: &SpotPrices,
        slow_prices_a_usdc: &Option<SpotPrices>,
        slow_prices_b_usdc: &Option<SpotPrices>,
        slow_prices_eth_usdc: &Option<SpotPrices>,
        slow_base_fee: u64,
        fast_chain: &Chain,
        fast_pair: &Pair,
        fast_protocol_component: Arc<ProtocolComponent>,
        fast_id: &state::PoolId,
        fast_height: u64,
        fast_swap_sim: Swap,
        max_slippage_bps: u64,
        congestion_risk_discount_bps: u64,
        fast_base_fee: u64,
        ignore_gas_costs_in_profit: bool,
        ignore_slippage_in_profit: bool,
        ignore_congestion_fee_in_profit: bool,
        ignore_usdc_conversion_in_profit: bool,
    ) -> eyre::Result<Self> {
        if slow_swap_sim.amount_out < fast_swap_sim.amount_in {
            eyre::bail!("Slow chain output is less than fast chain input");
        }

        let expected_profit = ExpectedProfit::try_from_swaps(
            &slow_swap_sim,
            &fast_swap_sim,
            slow_prices_a_usdc,
            slow_prices_b_usdc,
            slow_prices_eth_usdc,
            slow_base_fee,
            fast_base_fee,
            max_slippage_bps,
            congestion_risk_discount_bps,
            ignore_gas_costs_in_profit,
            ignore_slippage_in_profit,
            ignore_congestion_fee_in_profit,
            ignore_usdc_conversion_in_profit,
        )?;

        Ok(Self {
            slow_chain: slow_chain.clone(),
            slow_pair: slow_pair.clone(),
            slow_protocol_component: Some(slow_protocol_component),
            slow_height,
            slow_pool_id: slow_id.clone(),
            slow_swap_sim,
            fast_chain: fast_chain.clone(),
            fast_pair: fast_pair.clone(),
            fast_protocol_component: Some(fast_protocol_component),
            fast_height,
            fast_pool_id: fast_id.clone(),
            fast_swap_sim,
            slow_prices_a_b: slow_prices_a_b.clone(),
            slow_prices_a_usdc: slow_prices_a_usdc.clone(),
            slow_prices_b_usdc: slow_prices_b_usdc.clone(),
            expected_profit,
            max_slippage_bps,
            congestion_risk_discount_bps,
            slow_prices_eth_usdc: slow_prices_eth_usdc.clone(),
            slow_base_fee,
            fast_base_fee,
        })
    }

    pub fn try_promote(&self) -> eyre::Result<Trade> {
        let Self {
            slow_chain,
            slow_protocol_component,
            slow_swap_sim,
            fast_chain,
            fast_protocol_component,
            fast_swap_sim,
            ..
        } = self;

        let slow_solution = {
            let slow_component = slow_protocol_component
                .clone()
                .ok_or_eyre("missing protocol component")?
                .as_ref()
                .clone();
            create_solution(slow_component, slow_swap_sim, slow_chain.signer().clone())?
        };
        let slow_unsigned_tx =
            UnsignedTransaction::try_from_solution(&slow_solution, slow_chain)
                .wrap_err("Failed to create unsigned transaction from slow solution")?;

        let fast_solution = {
            let fast_component = fast_protocol_component
                .clone()
                .ok_or_eyre("missing protocol component")?
                .as_ref()
                .clone();
            create_solution(fast_component, fast_swap_sim, fast_chain.signer().clone())?
        };

        let fast_unsigned_tx =
            UnsignedTransaction::try_from_solution(&fast_solution, fast_chain)
                .wrap_err("Failed to create unsigned transaction from fast solution")?;

        Ok(Trade::new(self.clone(), slow_unsigned_tx, fast_unsigned_tx))
    }
}

impl Display for CrossChainSingleHop {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // TODO: get rid of this
        let max_slippage_slow = &self.slow_swap_sim.amount_out
            - bps_discount(&self.slow_swap_sim.amount_out, self.max_slippage_bps);
        let max_slippage_fast = &self.fast_swap_sim.amount_out
            - bps_discount(&self.fast_swap_sim.amount_out, self.max_slippage_bps);

        write!(
            f,
            "🐌 Slow Chain:
                Chain: {}
                Pair: {}
                Height: {}
                ID: {}
                Amount In: {}
                Amount Out: {}
                Max Slippage: {}
            🐇 Fast Chain:
                Chain: {}
                Pair: {}
                Height: {}
                ID: {}
                Amount In: {}
                Amount Out: {}
                Max Slippage bps: {}
            Expected Profit: {}
            ",
            self.slow_chain,
            self.slow_pair,
            self.slow_height,
            self.slow_pool_id,
            self.slow_swap_sim.amount_in,
            self.slow_swap_sim.amount_out,
            max_slippage_slow,
            self.fast_chain,
            self.fast_pair,
            self.fast_height,
            self.fast_pool_id,
            self.fast_swap_sim.amount_in,
            self.fast_swap_sim.amount_out,
            max_slippage_fast,
            self.expected_profit
        )
    }
}
