[package]
name = "kuma-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
kuma-core = { path = "../core" }

sqlx = { workspace = true, features = [
    "postgres",
    "runtime-tokio-native-tls",
    "chrono",
] }
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
num-bigint = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-error = { workspace = true }
color-eyre = { workspace = true }
figment = { workspace = true, features = ["yaml", "env"] }
tower-http = { workspace = true, features = ["cors"] }

[patch.crates-io]
svm-rs-builds = "0.8.31"

[dev-dependencies]
axum-test = "18.0.0-rc3"
serde_urlencoded = "0.7"
