name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Run cargo check
        run: cargo check

      - name: Run cargo build
        run: cargo build --release
      
      - name: Install just
        uses: taiki-e/install-action@just
      
      - name: run just fmt
        run: |
          just fmt
